const ivy_seed = 'WKOVC9KWZZYKB9DGVMDZUPXFEESSHYBINMWCLYRDZYTI9CAGTUHRNQMGOFS9WDOTXVKKUYW9GQVEGYK9E';
const cindy_seed = 'NYDQQWXEZMIZWJSHHIXZQ9EGMVSAMYESOAVTBYJWB9IEXFXNR9ISFUJNLXWATFPYH9RJGMEMGJZNMSECM';
const peggie_seed = 'KR9GJVSHHHLGY9GIEYFH9KJVZ9NFW9WEP9ZBPMNSHYNXIUEQZUXEJIEUPAUJ9WNWTW9IRQF9HCPMFPW9B';

module.exports = {
    ivy_seed,
    cindy_seed,
    peggie_seed
};
